"""Structural validation for migration 0006.

Verifies upgrade/downgrade operations without a live database by
inspecting the Alembic ops generated by the migration functions.
"""

import importlib
from unittest.mock import MagicMock

import pytest

# Migration modules have numeric names — use importlib and patch the
# module attribute directly since @patch string paths reject digit-leading names.
_mod = importlib.import_module(
    "migrations.versions.0006_add_dedup_and_nlp_columns"
)

EXPECTED_COLUMNS = [
    "simhash",
    "canonical_event_id",
    "corroboration_count",
    "nlp_relevance",
    "nlp_summary",
    "fatalities",
]


@pytest.fixture()
def mock_op(monkeypatch):
    op = MagicMock()
    monkeypatch.setattr(_mod, "op", op)
    return op


def test_upgrade_adds_all_columns(mock_op: MagicMock) -> None:
    _mod.upgrade()

    added = [c.args[1].name for c in mock_op.add_column.call_args_list]
    assert added == EXPECTED_COLUMNS


def test_upgrade_creates_fk_constraint(mock_op: MagicMock) -> None:
    _mod.upgrade()

    mock_op.create_foreign_key.assert_called_once()
    fk_call = mock_op.create_foreign_key.call_args
    assert fk_call.args[0] == "fk_events_canonical_event_id"
    assert fk_call.args[3] == ["canonical_event_id"]
    assert fk_call.args[4] == ["id"]


def test_upgrade_creates_simhash_index(mock_op: MagicMock) -> None:
    _mod.upgrade()

    mock_op.create_index.assert_called_once_with(
        "ix_events_simhash",
        "events",
        ["simhash"],
        schema="osint",
    )


def test_downgrade_drops_constraint_before_column(mock_op: MagicMock) -> None:
    _mod.downgrade()

    mock_op.drop_constraint.assert_called_once_with(
        "fk_events_canonical_event_id", "events", schema="osint"
    )

    dropped = [c.args[1] for c in mock_op.drop_column.call_args_list]
    assert "canonical_event_id" in dropped

    # constraint must be dropped before the column
    all_calls = mock_op.method_calls
    constraint_idx = next(
        i for i, c in enumerate(all_calls) if c[0] == "drop_constraint"
    )
    column_idx = next(
        i
        for i, c in enumerate(all_calls)
        if c[0] == "drop_column" and c[1][1] == "canonical_event_id"
    )
    assert constraint_idx < column_idx


def test_downgrade_drops_all_columns(mock_op: MagicMock) -> None:
    _mod.downgrade()

    dropped = [c.args[1] for c in mock_op.drop_column.call_args_list]
    for col in EXPECTED_COLUMNS:
        assert col in dropped
